version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27021:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hqXzNv2f5YC45veW
    volumes:
      - mongovolume:/data/db

  mongoexpress:
    image: mongo-express
    ports:
      - "6081:8081"
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=hqXzNv2f5YC45veW
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hqXzNv2f5YC45veW
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    links:
      - mongo

  # azure-storage:
  #   image: mcr.microsoft.com/azure-storage/azurite:latest
  #   restart: always
  #   command: "azurite-blob --loose --blobHost 0.0.0.0"
  #   ports:
  #     - "10001:10001"
  #     - "10000:10000"
  #   volumes:
  #     - blobstoragedata:/data"

  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    volumes:
      - "./api/src:/usr/src/app/src"
    environment:
      - MONGO_URI=mongodb://root:hqXzNv2f5YC45veW@mongo:27017/ett?authSource=admin
    restart: unless-stopped
    links:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - "./frontend/src:/usr/src/app/src"
      - "./frontend/index.html:/usr/src/app/index.html"
      - "./frontend/vite.config.js:/usr/src/app/vite.config.js"
    restart: unless-stopped

  forms-service:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    links:
      - api
      - frontend
    ports:
      - "8080:80"

volumes:
  mongovolume:
